server:
  port: 9010

spring:
  application:
    name: address-service
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: pass
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database: postgresql
    properties.hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect