server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://host.docker.internal:9005"
            allowedMethods:
              - GET
              - POST
#              - DELETE
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products(?<segment>.*), /$\{segment}
            - JwtTokenFilter
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart(?<segment>.*), /$\{segment}
            - JwtTokenFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>.*), /$\{segment}
            - JwtTokenFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<segment>.*), /$\{segment}
            - JwtTokenFilter
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - RewritePath=/address(?<segment>.*), /$\{segment}
            - JwtTokenFilter
        - id: gateway-service
          uri: lb://gateway-service
          predicates:
            - Path=/actuator/**
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/, /scripts/**, /**
          filters:
            - JwtTokenFilter
