server:
  port: 9009

spring:
  application:
    name: order-service
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: pass
  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    show-sql: true
    properties. hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true