server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9012/realms/master/protocol/openid-connect/token/introspect
          client-id: gateway
          client-secret: Ml9YusPYU8d4MdtOZY64JlgU1GdyJq0e

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9005"
            allowedMethods:
              - GET
              - POST
#              - DELETE
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products(?<segment>.*), /$\{segment}
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<segment>.*), /$\{segment}
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - RewritePath=/address(?<segment>.*), /$\{segment}
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/, /scripts/**, /**
